default:
  image: fedora:latest

build-job:
  before_script:
    - dnf install -y tmt
  script:
    - tmt -vvv --feeling-safe run --all provision --how local > tmt.log 2>&1
  artifacts:
    paths:
      - tmt.log
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch
