on: [push]
jobs:
  # grub2-build-koji:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: ./bootstrap
  #     - run: |
  #         ./configure --build=x86_64-redhat-linux-gnu \
  #         --host=x86_64-redhat-linux-gnu \
  #         --program-prefix= \
  #         --disable-dependency-tracking \
  #         --prefix=/usr --exec-prefix=/usr \
  #         --bindir=/usr/bin \
  #         --sbindir=/usr/sbin \
  #         --sysconfdir=/etc \
  #         --datadir=/usr/share \
  #         --includedir=/usr/include \
  #         --libdir=/usr/lib \
  #         --libexecdir=/usr/libexec \
  #         --localstatedir=/var \
  #         --runstatedir=/run \
  #         --sharedstatedir=/var/lib \
  #         --mandir=/usr/share/man \
  #         --infodir=/usr/share/info \
  #         'CC=gcc -fPIE -Wl,-z,noexecstack -Wl,--no-warn-rwx-segments' \
  #         'HOST_CFLAGS=-fno-strict-aliasing -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -m64 -mtune=generic -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -fcf-protection' \
  #         HOST_CPPFLAGS=-I/builddir/build/BUILD/grub-2.06/grub-x86_64-efi-2.06 \
  #         'HOST_LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,--build-id=sha1 -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' \
  #         'TARGET_CFLAGS=-fno-strict-aliasing -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -m64 -mtune=generic -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer' \
  #         TARGET_CPPFLAGS=-I/builddir/build/BUILD/grub-2.06/grub-x86_64-efi-2.06 \
  #         'TARGET_LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--no-warn-rwx-segments -static' \
  #         --with-rpm-version=2.06-108.fc38 \
  #         --with-platform=efi \
  #         --with-utils=host \
  #         --target=x86_64-redhat-linux-gnu \
  #         --with-grubdir=grub2 \
  #         --program-transform-name=s,grub,grub2, \
  #         --disable-werror
  #     - run: make
  grub2-build-upstream-with-utils-host-param:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./bootstrap
      - run: ./configure --with-utils=host
      - run: make
  grub2-build-upstream-without-params:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./bootstrap
      - run: ./configure
      - run: make
